src/fussy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LoginView,PasswordResetView,LogoutView

from menus.views import HomeFeedView

from profiles.views import activateProfileView,ProfileFollowToggle,AnotherProfileToToggle,RegisterView
# from Profils.views import UserFollowToggle

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', TemplateView.as_view(template_name='home.html'),name="home"),
    url(r'^$', HomeFeedView.as_view(),name="home"),
    url(r'^contact/$',TemplateView.as_view(template_name='contact.html'),name="contact"),
    url(r'^register/$',RegisterView.as_view(),name='register'),
    url(r'^activation/(?P<code>[\w-]+)/$',activateProfileView,name='activate'),
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^logout/$',LogoutView.as_view(),name='logout'),
    url(r'^profile-follow/$',ProfileFollowToggle.as_view(),name='follow'),
    # url(r'^profile-folgen/$',AnotherProfileToToggle.as_view(),name='folgen'),
    # url(r'^profile-folgen/$',UserFollowToggle.as_view(),name='folgen'),
    url(r'^password/$',PasswordResetView.as_view(),name='password_reset'),
    url(r'^about/$',TemplateView.as_view(template_name='about.html'),name="about"),
    url(r'^restaurants/', include('restaurants.urls',namespace="restaurants")),
    url(r'^items/', include('menus.urls',namespace="menus")),
    url(r'^profile/', include('profiles.urls',namespace="profile")),

]

src/menus/urls.py
from django.conf.urls import url

from .views import (
	ItemListView,
	ItemDetailView,
	ItemCreateView,
	ItemUpdateView,
)

urlpatterns = [
    url(r'^$',ItemListView.as_view(),name="list"),
    url(r'^create/$',ItemCreateView.as_view(),name="create"),
    # url(r'^(?P<pk>\d+)/edit/$',ItemUpdateView.as_view(), name="edit"),
    url(r'^(?P<pk>\d+)/$',ItemUpdateView.as_view(), name="detail"),
]

src/menus/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.
from restaurants.models import RestaurantLocation

User = settings.AUTH_USER_MODEL
class Item(models.Model):
	# Menu Item Association Info
	user 		= models.ForeignKey(User)
	restaurant 	= models.ForeignKey(RestaurantLocation)
	# Menu Item Info
	name 		= models.CharField(max_length=120)
	contents 	= models.TextField(help_text='Separate each item by comma')
	exclude 	= models.TextField(blank=True, null=True,help_text='Separate each item by comma')
	public 		= models.BooleanField(default=True)
	timestamp 	= models.DateTimeField(auto_now_add=True)
	updated 	= models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ['-updated','-timestamp']

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse("menus:detail", kwargs={"pk":self.pk})

	def get_contents(self):
		return self.contents.split(",")

	def get_exclude(self):
		return self.exclude.split(",")

src/menus/forms.py
from django import forms

from .models import Item

from restaurants.models import RestaurantLocation

class ItemForm(forms.ModelForm):
	class Meta:
		model = Item
		fields = [
		'restaurant',
		'name',
		'contents',
		'exclude',
		'public'
		]

	def __init__(self,user=None,*args,**kwargs):
		# a = kwargs.pop('text',None)
		# print(a)
		super(ItemForm,self).__init__(*args,**kwargs)
		# This will return a filter queryset , otherwise the returned queryset would be "RestaurantLocation.objects.all()"
		self.fields['restaurant'].queryset = RestaurantLocation.objects.filter(owner = user)#.exclude(item__isnull=False)

src/menus/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView


from .forms import ItemForm
from .models import Item

class HomeFeedView(LoginRequiredMixin,View):
	def get(self,request,*args,**kwargs):
		user = request.user
		is_following = [x.user.id for x in user.is_following.all()]
		qs = Item.objects.filter(user__id__in=is_following,public=True)[:4]
		template = 'menus/home-feed.html'
		context = {"object_list":qs,}
		return render(request,template,context)

class ItemListView(ListView):
	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)

	def get_context_data(self,**kwargs):
		context = super().get_context_data(**kwargs)
		return context

class ItemDetailView(DetailView):

	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)


class ItemCreateView(LoginRequiredMixin,CreateView):
	# This form would be passed to the template below.
	form_class = ItemForm
	# This template is saved at the src template folder.
	template_name = "form.html"

	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)

	def form_valid(self,form):
		instance = form.save(commit=False)
		instance.user = self.request.user
		return super().form_valid(form)

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs["user"] = self.request.user
		# kwargs["text"] = "Hello there"
		return kwargs

	def get_context_data(self,*args,**kwargs):
		context = super().get_context_data(**kwargs)
		context['title'] = "Add Menu Item"
		return context


class ItemUpdateView(LoginRequiredMixin,UpdateView):
	form_class = ItemForm
	# template_name = "form.html"
	template_name = "menus/detail-update.html"

	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)

	def get_context_data(self,*args,**kwargs):
		context = super().get_context_data(**kwargs)
		context["title"] = "Edit Menu Item"
		return context

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs["user"] = self.request.user
		return kwargs

src/menus/templates/menus/detail-update.html
{% extends 'base.html' %}

{% block head_title %} {{ object.name}} | Menu Item {% endblock head_title %}


{% block content %}

<br>

<h4>Item Name: {{ object.name }}</h4>
<p>Restaurant: {{ object.restaurant}} </p>
Created on {{ object.timestamp }} , Updated  {{ object.updated | timesince}} ago.
<br>

{% if object.get_contents %}
	Contents
	<ul>
		{% for item in object.get_contents %}
			<li>{{ item }}</li>
		{% endfor %}
	</ul>
{% endif %}

{% if object.get_exclude %}
	Exclude
	<ul>
		{% for item in object.get_exclude %}
			<li>{{ item }}</li>
		{% endfor %}
	</ul>
{% endif %}


<hr>

<h3>Make Changes</h3>
{% include 'snippets/form-snippet.html' with form=form %}

{% endblock content %}

src/menus/templates/menus/home-feed.html
{% extends 'base.html' %}

{% block content %}

<h3 align="center">User Following Feed</h3>

{% for obj in object_list %}

	<div class="container">
		<div class="row">
			<div class="col-sm-6 col-sm-offer-6">
				<div class="card">
					<ul>
						<a href="{% url 'profile:detail' username=obj.user %}">{{ obj.user }}</a>
						<li>{{ obj.restaurant }} <a href="">{{ obj.restaurant.location }}</a></li>
						<ul>
							<p>Item name: {{ obj.name }}</p>
								{% for ing in obj.get_contents %}
									<li>{{ ing }}</li>
								{% endfor  %}
						</ul>
					</ul>
				</div>
			</div>
		</div>
	</div>

{% endfor %}

{% endblock %}

src/menus/templates/menus/item_detail.html
{% extends 'base.html' %}

{% block content %}

<h4>Item Name: {{ object.name }}</h4>
<p>Restaurant: {{ object.restaurant}} </p>

{% if object.get_contents %}
	Contents
	<ul>
		{% for item in object.get_contents %}
			<li>{{ item }}</li>
		{% endfor %}
	</ul>
{% endif %}

{% if object.get_exclude %}
	Exclude
	<ul>
		{% for item in object.get_exclude %}
			<li>{{ item }}</li>
		{% endfor %}
	</ul>
{% endif %}

{% endblock %}

src/menus/templates/menus/item_list.html
{% extends 'base.html' %}


{% block content %}

<br>

<h3>Menu Items <small><a href="{% url 'menus:create' %}">Add</a></small></h3>

<ul>
{% for obj in object_list %}

	<li><a href="{{ obj.get_absolute_url }}">{{ obj.name }}</a><br></li>
	{% if obj.get_contents %}
	Contents
	<ul>
		{% for item in obj.get_contents %}
		<li> {{ item }}</li>
		{% endfor %}
	</ul>
	{% endif %}

	{% if obj.get_exclude %}
	Exclude
	<ul>
		{% for item in obj.get_exclude %}
		<li> {{ item }}</li>
		{% endfor %}
	</ul>
	{% endif %}

	{% empty %}
	<a href="{% url 'menus:create' %}">Add Item</a>

	
{% endfor %}
</ul>

{% endblock %}