src/fussy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LoginView,PasswordResetView,LogoutView

from menus.views import HomeFeedView

from profiles.views import activateProfileView,ProfileFollowToggle,AnotherProfileToToggle,RegisterView
# from Profils.views import UserFollowToggle

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', TemplateView.as_view(template_name='home.html'),name="home"),
    url(r'^$', HomeFeedView.as_view(),name="home"),
    url(r'^contact/$',TemplateView.as_view(template_name='contact.html'),name="contact"),
    url(r'^register/$',RegisterView.as_view(),name='register'),
    url(r'^activation/(?P<code>[\w-]+)/$',activateProfileView,name='activate'),
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^logout/$',LogoutView.as_view(),name='logout'),
    url(r'^profile-follow/$',ProfileFollowToggle.as_view(),name='follow'),
    # url(r'^profile-folgen/$',AnotherProfileToToggle.as_view(),name='folgen'),
    # url(r'^profile-folgen/$',UserFollowToggle.as_view(),name='folgen'),
    url(r'^password/$',PasswordResetView.as_view(),name='password_reset'),
    url(r'^about/$',TemplateView.as_view(template_name='about.html'),name="about"),
    url(r'^restaurants/', include('restaurants.urls',namespace="restaurants")),
    url(r'^items/', include('menus.urls',namespace="menus")),
    url(r'^profile/', include('profiles.urls',namespace="profile")),

]

src/menus/urls.py
from django.conf.urls import url

from .views import (
	ItemListView,
	ItemDetailView,
	ItemCreateView,
	ItemUpdateView,
)

urlpatterns = [
    url(r'^$',ItemListView.as_view(),name="list"),
    url(r'^create/$',ItemCreateView.as_view(),name="create"),
    # url(r'^(?P<pk>\d+)/edit/$',ItemUpdateView.as_view(), name="edit"),
    url(r'^(?P<pk>\d+)/$',ItemUpdateView.as_view(), name="detail"),
]

src/templates/snippets/css.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

src/templates/snippets/form-snippet.html
{% load crispy_forms_tags %}
{% if form.errors %}
	{{ form.error }}
{% endif %}

<form method="POST">{% csrf_token %}
	{{ form|crispy }}
	<button class="btn btn-primary" type="input">Submit</button>
</form>

src/templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

src/templates/snippets/nav.html
<div class="container">
	<h1>Fussy.com</h1>
	<a href="{% url 'home' %}">Home</a>
	<a href="{% url 'about' %}">About</a>
	<a href="{% url 'contact' %}">Contact</a>
	{% if request.user.is_authenticated %}	
		<a href="{% url 'restaurants:list' %}">Restaurants</a>
		<a href="{% url 'menus:list' %}">Menu Items</a>
	{% endif %}
</div>

src/templates/snippets/sidebar.html
<ul>
	<li>Item 1</li>
	<li>Item 2</li>
</ul>